server:
  port: 2018

spring:
  application:
    name: plant-asset-service
  data:
    mongodb:
      host: localhost
      port: 27099
      database: test2
#spring.data.mongodb.username=
#spring.data.mongodb.password=

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

# ============================
 # Sl4j
# ============================
logging:
  level:
    com:
      example:
        app: DEBUG
    root: WARN
    org:
      springframework: WARN
  file: d:/logs/myapps.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} %L - %msg%n'
