server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://bhanubilla@bitbucket.org/bhanubilla/config-repo.git
 #         username: ${github.username}
          username: bhanubilla
 #         password: ${github.password}
          password: 'Bills@#2020'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    
logging:
  level:
    org.springframework.cloud.config: DEBUG
